package ca.ulaval.glo2004.gui.events;

/**
 * This enum represents the different events that can be triggered by the application.
 */
public enum EventType {
    SELECTED_ITEM_CHANGED, WALL_DIMENSIONS_CHANGED, ACCESSORY_ADDED_OR_REMOVED, ACCESSORY_MODIFIED, VIEW_CHANGED,
    GRID_DISTANCE_CHANGED, GRID_TOGGLED, WALL_THICKNESS_CHANGED, IMPRECISION_CHANGED, ROOF_ORIENTATION_CHANGED,
    NEW_PROJECT, MIN_DISTANCE_CHANGED, ROOF_ANGLE_CHANGED, ZOOM_IN, ZOOM_OUT, SHOW_ALL_PANELS_CHANGED
}
